### ISSUE TITLE
[feature] Prefill rename dialog with current symbol name

### ISSUE THREAD

**Issue by sebthom** [eclipse/lsp4e#106]
When using **ALT+SHIFT+R** to rename e.g. a field or method, the rename dialog does not prefill the current name nor has any context information on what is going to be renamed: 
![image](https://user-images.githubusercontent.com/426959/163624320-84f1a553-3dc6-4e7f-89f3-bcb9973d33c2.png)

It would be nice to have the current name in the **New Name** field as default instead of the `newName` placeholder.

**Comment by PyvesB** [comment]
I implemented this a while back in ade065d0001054240666d205b6542a4fd1da35eb. The language server must support the [prepareRename](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#textDocument_prepareRename) request. You can test this out with the [Eclipse Ruby integration](https://github.com/PyvesB/eclipse-solargraph) for example. 😉

**Comment by mickaelistria** [comment]
@sebthom How happy are you with @PyvesB 's answer? If this can work for you, then please close.

**Comment by sebthom** [comment]
In theory yes, practically not really as it does not even seem to work for typescript files in Wild Web Developer, so either the adoption rate of prepareRename request in language servers is low or something is still broken.

**Comment by mickaelistria** [comment]
> it does not even seem to work for typescript files in Wild Web Developer

The typescript-language-server used by Wild Web Developer is not a very hot project. As VSCode and most "official" TypeScript tools to directly rely on tsserver (which does not support LSP https://github.com/microsoft/TypeScript/issues/39459 ), the typescript-language-server doesn't really catch on as fast and misses some features of LSP.
Some other language servers (eg Ruby integration linked by @PyvesB , rust-analyzer used by Corrosion) do use prepareRename successful.
So unless you can give it a try and confirm this is broken, I think we can close the issue.

**Comment by sebthom** [comment]
The RenameCapabilities configured in LanguageServerWrapper are not indicating support for prepareRename. That's why the rename dialog is not prefilled. This however is required by the spec, see https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/
```typescript
/**
 * The server provides rename support. RenameOptions may only be
 * specified if the client states that it supports
 * `prepareSupport` in its initial `initialize` request.
 */
renameProvider?: boolean | RenameOptions;
```

**Comment by mickaelistria** [comment]
Thanks @sebthom . Do you plan to provide a PR for that?
